### ISSUE TITLE
Error while trying to run npm run dev

### ISSUE THREAD

**Issue by parthvshah** [pes-alcoding-club/editorials#6]
After running `npm install` in the directory, I am not able to run the dev server. Following is the error it shows:

```
TypeError: Cannot read property 'access' of undefined
    at fileExists (/mnt/c/Users/Parth/Documents/editorials/node_modules/next/dist/lib/file-exists.js:1:211)
    at verifyTypeScriptSetup (/mnt/c/Users/Parth/Documents/editorials/node_modules/next/dist/lib/verifyTypeScriptSetup.js:1:3167)
    at DevServer.prepare (/mnt/c/Users/Parth/Documents/editorials/node_modules/next/dist/server/next-dev-server.js:10:1908)
    at then (/mnt/c/Users/Parth/Documents/editorials/node_modules/next/dist/cli/next-dev.js:21:369)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Any ideas?

npm version: 6.14.6
node version: v8.10.0
WSL

**Comment by souravtecken** [comment]
Seems to be an issue with your node version, I was able to replicate the error on v8.10.0, so updating node should fix that issue. I'm currently on v12.18.2

**Comment by parthvshah** [comment]
Thanks. I'll add the current versions in the README in the next commit.
